# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='brand_images')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
