# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id_filter', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(default=None, max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('specific', models.TextField(blank=True, default=None, null=True, verbose_name='Характеристики')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Входит в топ продаж')),
                ('sale', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cкидка')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка в процентах')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Цена со скидкой')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Производитель')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='FilterImage',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='filters_images')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('filter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filters.Filter', verbose_name='Фильтр')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
