# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
