# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_filter_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры'},
        ),
        migrations.AlterField(
            model_name='filter',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
