# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20171127_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='image',
        ),
        migrations.AlterField(
            model_name='filter',
            name='article',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='specific',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
